export const dummyLeaves = [
    {
        count: 28,
        type: 'available leaves',
        color: 'blue-100'
    },
    {
        count: '08',
        type: 'sick leaves',
        color: 'green-100',
    },
    {
        count: 14,
        type: 'casual leaves',
        color: 'purple-100',
    },
    {
        count: '06',
        type: 'earned leaves',
        color: 'pink-100',
    },
]

export const dummyLeaveRequests = [
  {
    id: 1,
    type: 'Casual Leave',
    from: '18/04/2026',
    to: '19/04/2026',
    days: 2,
    reason: 'Going home',
    approved_by: 'Admin',
    status: 'rejected',
  },
  {
    id: 2,
    type: 'Sick Leave',
    from: '05/04/2026',
    to: '06/04/2026',
    days: 2,
    reason: 'Fever and cold',
    approved_by: 'HR',
    status: 'approved',
  },
  {
    id: 3,
    type: 'Earned Leave',
    from: '10/04/2026',
    to: '15/04/2026',
    days: 6,
    reason: 'Family trip',
    approved_by: 'Manager',
    status: 'pending',
  },
  {
    id: 4,
    type: 'Casual Leave',
    from: '22/04/2026',
    to: '22/04/2026',
    days: 1,
    reason: 'Personal work',
    approved_by: 'Admin',
    status: 'approved',
  },
  {
    id: 5,
    type: 'Sick Leave',
    from: '12/04/2026',
    to: '14/04/2026',
    days: 3,
    reason: 'Medical rest',
    approved_by: 'HR',
    status: 'rejected',
  },
  {
    id: 6,
    type: 'Earned Leave',
    from: '25/04/2026',
    to: '30/04/2026',
    days: 6,
    reason: 'Vacation',
    approved_by: 'Manager',
    status: 'pending',
  },
  {
    id: 7,
    type: 'Casual Leave',
    from: '02/04/2026',
    to: '03/04/2026',
    days: 2,
    reason: 'Family function',
    approved_by: 'Admin',
    status: 'approved',
  },
  {
    id: 8,
    type: 'Sick Leave',
    from: '16/04/2026',
    to: '17/04/2026',
    days: 2,
    reason: 'Headache',
    approved_by: 'HR',
    status: 'pending',
  },
]; 

export const dummyActivities = [
    {
      id: 1,
      type: 'created',
      user: 'Rahul',
      message: 'created task "Prepare salary report"',
      task: 'task-1',
      time: '2 mins ago',
    },
    {
      id: 2,
      type: 'moved',
      user: 'Anita',
      message: 'moved task to In Progress',
      time: '10 mins ago',
      task: 'task-2',
    },
    {
      id: 3,
      type: 'deleted',
      user: 'Rohit',
      message: 'moved task to In Progress',
      time: '10 mins ago',
      task: 'task-3',
    },
  ];